### ISSUE TITLE
Fix margin in "Highlights" section, between the link and the description

### ISSUE THREAD

**Issue by ivancea** [ivancea/mac-renderer#11]
![imagen](https://github.com/ivancea/mac-renderer/assets/5280509/dfb6e7d2-8352-474f-abd6-c564958d194b)

**Comment by maheshchandra10** [comment]
I guess you want to have a gap between the link and the description.
Any preferences on how much pixels of gap required?

**Comment by ivancea** [comment]
> I guess you want to have a gap between the link and the description. Any preferences on how much pixels of gap required?

@maheshchandra10  It should have the same as the other sections, that already have it. I've just seen the issue, I don't know if it happens always, I wish it does.

That said, this is a quite niche repository! You're of course welcome to contribute, but I wouldn't recommend unless you use the [Manfred service](https://www.getmanfred.com/) to host your CV 👀
